//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblExperience
    {
        public int ID { get; set; }
        public string Head { get; set; }
        public string SubHead { get; set; }
        public string Explanation { get; set; }
        public string Date { get; set; }
    }
}
